name: Quake Monitor

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Create Key File
        run: echo '${{ secrets.FIREBASE_KEY }}' > quake-station-firebase-adminsdk-fbsvc-a63034f825.json

      - name: Execute Quake Monitor
        run: node quake-monitor.js